name: Mock Test CI/CD Pipeline

on:
  pull_request: # プルリクエスト(マージするブランチ)をトリガー # "mainブランチに対するプルリクエストが作成・更新されたとき" にワークフローが実行される
    branches: [ main ]
  
  pull_request_target: # マージ先のブランチをトリガー # "mainブランチがマージ先となるPRのイベント（例：外部リポジトリからのPR）" でワークフローが実行される
    branches: [ main ]
  
  workflow_dispatch: # 手動トリガー

env:
  DOCKER_IMAGE: langgraph-agentic-system-test

jobs:
  mock-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image for mock test
        uses: docker/build-push-action@v5
        with:
          context: ${{ github.workspace }}
          file: ./Dockerfile
          load: true
          tags: ${{ env.DOCKER_IMAGE }}:mocktest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Run mock tests in Docker
        run: |
          docker run --rm \
            ${{ env.DOCKER_IMAGE }}:mocktest pytest tests/test_mock_planner_agent.py -v